---
  - name: set server timezone
    copy: content='Europe/Athens'
          dest=/etc/timezone
          owner=root
          group=root
          mode=0644
          backup=yes
    notify:
        - update timezone          
